### ISSUE TITLE
sfdx force:package:install --package to accept LATEST placeholder

### ISSUE THREAD

**Issue by baksale** [forcedotcom/sfdx-core#165] opened 2019-08-14 20:09 UTC
**Is your feature request related to a problem? Please describe.**
In many CI/CD activities it is required to install latest package version (e.g. in java world there is a -SNAPSHOT placeholder which guarantees latest version).
We'd like to have the same with dx packages.
https://salesforce.stackexchange.com/questions/273531/sfdx-command-to-find-the-latest-package-version

**Describe the solution you'd like**
Given I have a package with `alias "My Model"`
When I run installation command like this 
`sfdx force:package:install --package "My Model@LATEST"`
Then sfdx finds latest created version for the package
And sfdx installs the found version

**Describe alternatives you've considered**
Alternatively, we might implement a plugin to find a version, but doesn't make sense to spread package versions-related commands across multiple plugins
As of now I'm using bash script in my CI/CD

**Additional context**

**Comment by baksale** [comment] 2019-08-20 06:51
Replicated request here as a more appropriate place
https://github.com/forcedotcom/cli/issues/153

**Comment by clairebianchi** [comment] 2019-11-12 21:47
Duplicate of forcedotcom/cli#153

Thank you @baksale for your feature request

**Closed by clairebianchi** 2019-11-12 21:47 UTC
