### ISSUE TITLE
Invalid package version publish

### ISSUE THREAD

**Issue by jfaderanga** [forcedotcom/sfdx-core#677] opened 2022-10-12 23:55 UTC
### Summary

This [commit](https://github.com/forcedotcom/sfdx-core/commit/7bb86ff6209ccc5749f3ac9d774baa1693158246) shows version upgrade to 3.31.04 but [npm](https://www.npmjs.com/package/@salesforce/core) package (latest) shows 3.31.4. This makes plugins referencing the sfdx latest failed and throws an error [TypeError: Invalid Version: 3.31.04](https://github.com/scolladon/sfdx-git-delta/issues/368#top)

### Steps To Reproduce:

1. NPM package version should match version in package.json

### Expected result

1. NPM package version should be 3.31.04

### Actual result

1. NPM package version shows 3.31.4

**Comment by cromwellryan** [comment] 2022-10-13 02:24
Thank you to @jfaderanga for reporting this issue and for @brytonpilling for his comments on [the offending commit in `@salesforce/core`](https://github.com/forcedotcom/sfdx-core/commit/7bb86ff6209ccc5749f3ac9d774baa1693158246).

This issue occurred as a result of a build and release pipeline modifications being made for `sfdx` and `sf` infrastructure. This resulted in invalid [semver.org](https://semver.org/) versions of `sfdx-core` being released–specifically version [3.31.04](https://github.com/forcedotcom/sfdx-core/commit/7bb86ff6209ccc5749f3ac9d774baa1693158246). This resulted in failures in all non-bundled plugins, because their dependencies are resolved during install. Bundled plugins would not have been affected even for npm installs of `sfdx`, because [we now shrinkwrap sfdx](https://github.com/forcedotcom/cli/issues/1678).

To resolve this issue we have:

1. [Deprecated the offending version of `@salesforce/core`](https://www.npmjs.com/package/@salesforce/core/v/3.31.4).
2. Reverted our pipeline changes.
3. Released a [new version of `@salesforce/core`–version 3.31.8](https://www.npmjs.com/package/@salesforce/core/v/3.31.4?activeTab=versions)

We will leave this issue open until our regularly scheduled RC and GA release are published successfully on October 13th.

**Comment by cromwellryan** [comment] 2022-10-13 19:18
`sfdx` version [`7.173.0`](https://www.npmjs.com/package/sfdx-cli/v/7.173.0), today's RC, is out. With [@salesforce/core](https://github.com/forcedotcom/sfdx-core) settled and [sfdx-git-delta](https://github.com/scolladon/sfdx-git-delta) confirmed on both stable and rc versions of `sfdx`, I'm going to close this issue.

Thanks again for the help and sorry we interrupted your work.

**Closed by cromwellryan** 2022-10-13 19:18 UTC
